name: CI
on: 
  push:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup node
        uses: actions/setup-node@v4
        with: 
          node-version: 22
      
      - name: Install Dependencies
        run: npm Install

      - name: Run Tests
        run: npm test

  
